export const COMMUNITY_SECTION = [
  {
    title: 'What IS a community?',
    nav: 'Definitions',
    question: '',
    quotes: [
      {
        tagline: 'Community limitations',
        quote: '<strong>I want to believe that our communities can do everything</strong>, that our communities can be everything that we want and need them to be... They are sort of this dream that we could exist outside of the world as it exists right now and outside of particularly the way that states are using violence. And then it comes up against very real <strong>capacity issues, limits</strong> around what our skill bases actually are, what we\'re actually able to do, and follow through on.'
        + '<br><br>' + 'We talk about community and <strong>no one really knows what community is</strong>. We all kind of have this idea of what it is. "Oh, the community is responding and wants this and this and this" but really, just cuz we\'re a community doesn\'t mean that all of our <strong>power dynamics</strong> aren\'t going to play out. And we should expect them to play out. I think it\'s <strong>easy for us to idealize community</strong> and assume, "Well if the community wanted it then.. we\'re all good."'
        + '<br><br>' + 'For me, accountability is a lot of doing what you say you\'re gonna do, and sometimes I feel like in the transformative justice models, <strong>we\'re not actually able to do all the things that we want to do</strong>, or say we want to do.'
        + '<br><br>' + 'Is it better to be like, "Well, we\'ve got nothing" or is it better to be like, "We could try this thing and it probably is gonna be weird and I hope that it goes well and here are all the values its based on, which sounds really cool and in line with our values, but we don\'t really know how to do it yet."',
        personId: 4
      },
      {
        tagline: 'Personal networks vs. neighborhoods',
        quote: 'As a group we\'ve always had a commitment to being <strong>majority queer people of color</strong> and to focusing our interventions on the <strong>people who are most impacted by violence in our own communities</strong>. So it\'s been a priority to have our membership reflect that and that to be the community that we intend to serve. The Bay Area is big but the community here is small, so there are a lot of friends of friends going to the same kinds of events and knowing people in the same kinds of circles.'
        + '<br><br>' + 'Which, on the one hand, really benefits our work, because we\'ve always seen our interventions as starting with folks that we know, and starting from contexts that we know, rather than going into some wholly new situation and imposing whatever we think is right there. We\'ve always imagined that at least our first interventions are going to be with <strong>people in our own personal networks</strong>, and so I think it really serves us to have that shared community in that sense.'
        + '<br><br>' + 'This year we\'ve been having conversations about what community means and how do we want to use community and think about community. Lately, we\'ve been having talks around just using <strong>community as a descriptive location</strong> term and like trying to <strong>build more in the places we inhabit</strong>. We are maintaining those connections along lines of identity and interest but what would it mean to really focus our energies on <strong>bringing this work to our neighborhoods</strong> and the people who live down the street and the people who work in our offices?',
        personId: 16
      },
      {
        tagline: 'Beloved community',
        quote: '"What is community accountability" is very much a question of process and seems like it would always be, because <strong>communities are in process</strong>. I actually spoke at this gathering called "Whose Beloved Community?" in Atlanta last week. It was a gathering that was envisioned as part of this multi-year process of thinking about LGBT \'I think initially they languaged it LGBT, no Q, I\'m in there in the Q\' LGBT activism and history and the civil rights movement. Especially when you\'re talking in any kind of intersectional way, community is a term that is often used pre-maturely. So is there an LGBT community? Is that a queer community? Or not? Since maybe nobody\'s talking about queer in that frame? Is that a community that\'s actually <strong>collectively operational, let alone accountable</strong>, like operational for trans people, really? Is there a common that is functioning and operational, that is actually inclusive of who is supposedly named under the community?'
        + '<br><br>' + 'I think that there\'s a way that the <strong>term is used prematurely and really for convenience</strong>, like "people can be funded under these categories or people can be visible in these ways or people can be found or are supposed to know that they\'re invited because it\'s the community."'
        + '<br><br>' + 'I appreciated having the opportunity to think about it in the context of <strong>\'beloved community,\'</strong> which is a theological term and an aspirational term and explicitly about what is it to have community in the face of conflicts. How is that a vision and a dream and a possible practice, and not something that has already been achieved and that we can just now build on top of? How can we empower the community and how can we get rights for this community and how can we do this for that community, <strong>but is there a community?</strong>',
        personId: 1
      },
      {
        tagline: 'Supporting each other',
        quote: 'We were meeting every week for three hours and doing nothing but talking about ourselves and where we were at. You know, me and my partner that I was with when we started, we dated for five years, we broke up and it was devastating to me. I talked about it at the Support New York meetings, other people changed genders, went through these huge personal transitions, it was brutally intense and beautiful and just regular life stuff was going on that maybe people need communities to support them during. Whatever our sick fucking society, capitalist debt culture tries to, maybe not actively, maybe more insidiously, alienate people from one another and inhibit these kinds of bonds. <strong>So I genuinely don\'t know if I would still be alive if it wasn\'t for the kind of grounding and mental stuff that I had from Support New York</strong>. And being a local guy and having family nearby all the time doesn\'t hurt. And family, that\'s good people, but my community of friends was really important to keeping my mental health in check.'
        + '<br><br>' + '<strong>But we are seeing it more and more, the community that we are all a part of doesn\'t really exist anymore</strong>. Some of them are dead, some of them are like the bad kind of lawyer, all kinds of stuff happens. And so, at some point, we stopped meeting all the time, and we stopped checking in as intensely as we used to, then we stop checking in at all, like we only meet once in three months. We\'ve been doing perpetrator accountability process for 7 years. That\'s fucking crazy, that\'s nuts. Of course we stopped prioritizing checking in at some point, and we have to reexamine and reaffirm that it is something important to us because that\'s just the nature of anything. <strong>You have to always recommit</strong>, I think. You don\'t just say, \'I do this thing and I am gonna do this thing and then never interrogate it and never reexamine it ever again.\' You have to constantly be reexamining, reaffirming, recommitting, reestablishing boundaries, you know what I mean.',
        personId: 2
      },
      {
        tagline: 'Choosing the unchosen',
        quote: 'Students come to my office all the time and they\'ll take a critical race theory class with me and they\'ll be like, \'I believe you and this is all important but <strong>I still have to go home at the end of the day and my family still says this really terrible stuff</strong> that I don\'t know what to do with.\' And I think it would be a mistake to be like, \'You should leave them, you should disavow your family, that would be the truly anti-racist thing to do!\' (laughter). We don\'t choose those people, I don\'t choose these people and yet they\'re my family. <strong>What does it look like to choose what we have not been able to choose</strong>, and to decide that we\'re going to live differently in that, even if we can\'t make someone else think differently? <strong>How do we practice our own power and vulnerability</strong> in those situations and make them more apparent for ourselves?',
        personId: 3
      },
      {
        tagline: 'Building unwanted relationships',
        quote: 'Most of my neighbors are friendly and mostly look out for each other. But there\'s this one neighbor, that I honestly really can\'t stand. But I say to myself, "Okay Ejeris, you can\'t just silently sit in the elevator, you have to introduce yourself, you have to get to know this woman." She totally pushed all my buttons. She was really mad at me that I asked her to stop smoking in the elevator once, and she decided to make her case to me as to why she had the right to smoke in the elevator. I\'m an asthmatic, there\'s no case to be made.'
        + '<br><br>' + 'But <strong>even though I don\'t want to build a relationship with her</strong>, I don\'t like her, I would prefer that she move, I don\'t want bad things to happen to her. But she annoys me, she annoys the shit out of me. But it\'s part of the work. <strong>It\'s part of the work because she\'s going to be around if something happens to me. And I\'ll be around if something happens to her</strong>.',
        personId: 7
      },
      {
        tagline: 'Creating accountable communities?',
        quote: '<strong>What is needed to create accountable communities? What makes a community?</strong> Is it geography, identity, working together?'
        + '<br><br>' + 'One definition might be that communities are the <strong>people who are most likely to call you out</strong>, which would be political communities. But the problem that we saw with Occupy Wall Street was that it had a very broad purpose and brought a lot of people together, but that doesn\'t mean we\'re a community. <strong>If our basic needs aren\'t being met or our needs are really different, how can you be a community</strong>? There are so few spaces for intergenerational exchange and solidarity, so every generation is starting a new instead of learning from elders. From the community level, how do you build it up to create a global alternate system? Can you even scale this?',
        personId: 18
      },
      {
        tagline: 'Questions for community',
        quote: 'By \'communities\' of the oppressed we mean communities of shared daily living, or of shared history, or of shared identity, or of shared struggle or of shared resistance, or of shared visions. <strong>We often begin with communities that are at present not united or in solidarity, but fragmented, dispersed, and often not self-aware as communities. Solidarity is born of community investment</strong>. Community members experience degrees and forms of investment in a community: they experience a sense of place, of belonging, of support, of companionship, of shared strategies for survival, and, not infrequently, of shared identity.'
        + '<br><br>' + 'When we think of particular communities as we are in the process of creating Harm Free Zones we ask: '
        + '<br><br>' + 'How large is the community? Does it have more or less clear boundaries? If someone is mistreated by someone, how easy will it be to determine whether that person is a community member? How easy will it be to get some of the portions of the community together for discussion? Are there places for such gatherings? When was the last time that portions of the community got together for discussion? What is the relation between the community and particular community organizations? Do members of the community form part of the organizations? Do the organizations intervene in community conflicts? Do organizations have their own places for gatherings? Are community members invested in the community? In which ways? Do they rely on each other for help and advice? For childcare? To get things changed in the school, the health care they receive, etc.? Do people have a sense of the economics of the community? Do people know who are the people who hire people for particular kinds of jobs? How is money and other forms of support made? Where do people talk to each other? About what? What concerns them? What do they care about? Do they know that about themselves? To what extent do they think of each other as people they could rely on? What are the present roles of women in the community? Are women more active in community issues than men? How do the different groups making up a community get along? How do people get along with other communities?'
        + '<br><br>' + '-\"Building Harm Free Zones: An Organizing Booklet\", p. 8-9',
        personId: 27
      },
      {
        tagline: 'Building relationships in scary times',
        quote: 'I was living in a building, when I was working at ALP, where there was a rumor. The neighbors inside our building were all talking about how there was <strong>initiation going on for a street organization</strong>. One of the pieces for the initiation was to <strong>attack a gay person or a woman</strong>. In our neighborhood the buildings were all connected – so literally people were really afraid of folks walking over on the roof and trying to come through a window. We\'re like "Oh God, what are we gonna do." So we <strong>developed a plan</strong> where we were going to ask friends to stay over to support us.'
        + '<br><br>' + 'But what actually kind of <strong>shifted everything</strong> was that there was a really bad <strong>police shooting of a young Black man</strong> two blocks away. The next day, the whole community was out. Folks were pissed off, fucking angry, helicopters overhead, all of that. I decided not to go into work that day, cuz I really wanted to stay in community with my neighbors. So <strong>I just walked around talking to people</strong>, being like "What do you wanna do about this situation? What do you think we should do? How can we prevent this type of stuff? Do you want to get involved?" I had nothing to recruit them to because they were not necessarily explicitly either queer or into transformative justice, but there was a community meeting that happened afterwards and I was able to pass off some of the contacts I\'d met to another organization.'
        + '<br><br>' + '<strong>Some of the folks I met turned out to be some folks who lived next door</strong>. Who then were like, "You\'re cool, so I\'m cool with you." And those guys looked out for us and even intervened in some harassment that occurred against one of my roommates.'
        + '<br><br>' + 'So I think sometimes there\'s a piece around <strong>solidarity work</strong>. How are we building in spaces where it\'s not necessarily directly around our self interest? <strong>People show up if you show up</strong>. Those guys were doing the same thing [using threats as a community-based strategy], they were letting people know if they fucked with me, they were fucking with them. But I do think there\'s a piece around the relationship building that we do, and <strong>building even the scary relationships</strong>.',
        personId: 7
      },
      {
        tagline: 'Pods',
        quote: 'During the spring of 2014 the Bay Area Transformative Justice Collective (BATJC) began using the term \"pod\" to refer to a specific type of relationship within transformative justice (TJ) work. We needed a term to describe the kind of relationship between people who would turn to each other for support around violent, harmful and abusive experiences, whether as survivors, bystanders or people who have harmed. These would be the people in our lives that we would call on to support us with things such as our immediate and on-going safety, accountability and transformation of behaviors, or individual and collective healing and resiliency.'
        + '<br><br>' + 'Prior to this, we had been using the term \"community\" when we talked about transformative justice, but we found that, not surprisingly, many people do not feel connected to a \"community\" and, even more so, most people did not know what \"community\" meant or had wildly different definitions and understandings of \"community.\" '
        + '<br><br>' + '"<a href="https://batjc.wordpress.com/pods-and-pod-mapping-worksheet">Pod Mapping Worksheet</a>"'
        + '<br><br>' + '-Bay Area Transformative Justice Collective Blog',
        personId: 30
      },
      {
        tagline: 'Navigating class & gender',
        quote: '<strong>Violence and oppression break community ties and breed fear and distrust</strong>. At its core, the work of <strong>creating safety is to build meaningful, accountable relationships within our neighborhoods and communities</strong>. Within the S.O.S. Collective, we made it a point to do outreach in the immediate area after incidents of violence. While it often felt terrifying to talk about the work of preventing and ending violence against LGBTQ people of color, we built strong allies and had life-changing conversations. Time and time again I\'ve known people who were saved by the relationships they built. [\']'
        + '<br><br>' + 'This strategy is not without complications. For many people, particularly <strong>women and gender nonconforming people</strong>, the act of <strong>engaging with strangers can open us up to harassment and even violence</strong>. At the same time these challenges shouldn\'t prevent us from building relationships; they may merely shift the ways that we go about it. Attending community events is also a great way to build relationships.'
        + '<br><br>' + 'Additionally we must also be cognizant of the way that <strong>class, educational privilege, and gentrification</strong> can impact relationship building. Gentrification is its own form of violence within many low-income neighborhoods. Many gentrifiers\/newcomers can act fearful and do not shop within their communities, attend events, or build relationships with their neighbors. Gentrifiers\/newcomers who are also movement leaders tend to create movements and strategies that are not grounded within the lived experiences of the people most impacted by violence.'
        + '<br><br>' + 'While I don\'t believe that we can separate ourselves from our <strong>privileges</strong>, I think we can <strong>leverage them toward justice</strong>. My educational privilege and relationships mean that I know a lot of lawyers and have knowledge about our rights during police encounters. I\'ve made sure to share "know your rights" information with my neighbors, observe the cops alongside my neighbors, and given legal referrals. Through these moments I\'ve been able to build stronger relationships with my neighbors and deepen trust.'
        + '<br><br>' + '-from "<a href="http://www.truth-out.org/opinion/item/32489-building-community-safety-practical-steps-toward-liberatory-transformation">Building Community Safety: Steps Towards Liberatory Transformation.</a>" In Truthout, Aug. 15, 2015.',
        personId: 7
      },
      {
        tagline: 'Pockets of promise',
        quote: 'Under a microscope, in every place, there are <strong>pockets of promise</strong>, where there are enough people striving for mutual aid and social accountability, so I think [transformative justice is] possible, if people are more altruistic in their behaviour and motives',
        personId: 20
      }
    ]
  },
  {
    title: 'How have communities been involved in your work?',
    nav: 'Involvement',
    question: '',
    quotes: [
      {
        tagline: 'Women & Girls Community Action Network',
        quote: 'We [Women and Girls Community Action Network] started without an agenda, by and large. I mean there was an agenda of challenging the women\'s movement and building a different thing. But our agenda didn\'t include doing media justice work or healing organizing or community accountability even. It started with: <strong>"What would it look like if a different group of people other than the people who have traditionally run the women\'s movement got to define what the issue was, how they would want to respond to it, and got to take action and be the leaders?"<strong> Instead of having the ED of the local organization be the leader. We weren\'t even sure it would be around violence against women at first. It was like, what if a group of younger women got to just define the issues for themselves. Maybe we do reproductive justice work, maybe it\'s economic justice work, maybe it\'s something none of us have thought about. It was supposed to be a one year exploratory project.'
        + '<br><br>' +'What happened was when I met with adult women about it, like professors and members of different organizations, they were like "This is a good one year exploratory project. I would like to put out a report." And when I started meeting with <strong>youth<strong>, they were like "<strong>Let\'s just take action together. Why are we studying?"<strong>'
        + '<br><br>' +'It became a 501c3, so we were also part of the non-profit industrial complex. It had several different elements. There was a youth organizing piece called <strong>Females United for Action [FUFA]<strong>, organizing mostly high school students, some college students. FUFA in its early days took the stance that the <strong>reason there\'s so much violence against young women of color was media images of young women of color<strong>. So they did <strong>media justice work<strong>, which was really cool and powerful to watch. Then they became more interested in <strong>healing organizing<strong> and developing concepts around healing. And FUFA started out as a coalition of organizations, and then added individuals, and kind of changed back and forth: there were organizational members of youth groups and also individual young people.'
        + '<br><br>' +'FUFA also went through a lot of work around <strong>trans issues<strong>. FUFA at one point got approached by trans young women asking if they could join and then did a series of sessions on learning about trans oppression and shifted its focus. And actually in the last days of Women and Girls CAN, there were some discussions before I left about whether to change the name Women and Girls CAN because some people felt it didn\'t express being open to trans women and girls.'
        + '<br><br>' +'The <strong>community accountability group<strong> was a group, 7 or 8 women from all different perspectives, all interested in doing this work, some academic, some organizers, some from a social service perspective, all interested in trying to figure this piece out. So it was something more like a think tank than doing actual actions. We met regularly; it was half white women and half women of color. Very focused on <strong>racial justice<strong>. So if women of color couldn\'t make the meetings, we would cancel them. Trying to reflect on how much the women\'s movement in this country has been dominated by white women and really just shut out the voices of anyone who wasn\'t a middle- or upper-class heterosexual white woman. So we were trying to be really conscious of that. And that group put on a bunch of different workshops for the community and put out this writing piece ["Communities Engaged in Resisting Violence"], that came out of all of that. It was trying to document what was happening in Chicago and promote conversations and see if we could move things further. Those were always the two core projects.',
        personId: 6
      },
      {
        tagline: '"Consentivale" event',
        quote: 'Support NY has regularly held an <strong>event called the \'Consentivale\'</strong> which is a day-long event with workshops and talking about consent. You can work with people on an individual level, but you also have to do the <strong>broader outreach, preventing things</strong> before they happen. People don\'t have education around consent, so the more you can engage people to think about it broadly, the more it becomes common language, it becomes common procedure for people.',
        personId: 18
      },
      {
        tagline: 'Safe Outside the System training',
        quote: '[At the Audre Lorde Project] We started to organize local businesses and institutions, and recruit them. We didn\'t have a curriculum, we had to create a <strong>"How to Be Safe Outside the System" training</strong>.'
        + '<br><br>' + 'A lot of times these spaces were people who were not anti-LGBT folks, but just not really understanding [LGBT issues]. So the training included some <strong>basics on heterosexism, homophobia, transphobia</strong>, some info on the violence that had been happening in the neighborhood, some info that they were already deeply acquainted with about how police violence is flowing in the neighborhood.'
        + '<br><br>' + 'Then we would just do this facilitated discussion. So, if a fight broke out in your space, what would you do? If this happened, what would you do? <strong>Many of the businesses would assume they didn\'t have safety strategies, they did but weren\'t explicit to them.</strong> They were not written down, they were just in their head as \'this is what we did.\' So we wanted to do that to make it more explicit to them. We wanted to make sure those strategies included queer and trans folks of color. We wanted to have them have a sense of when and how violence can erupt, for instance, that you actually have to stop somebody with homophobic or transphobic language, because that will escalate.'
        + '<br><br>' + 'Then we\'d make a little plan with them about what they would do. But we felt really clear that we didn\'t feel we could build base if we forced them to sign on to the \'We will never call the police.\' <strong>It didn\'t feel fair to ask to do that when we didn\'t have another thing for them to call</strong>.'
        + '<br><br>' + 'They already were in many ways [practicing community-based strategies]. It was <strong>community-based strategies but it wasn\'t necessarily transformative</strong>. There was this one space that was like, "Well if things get really bad I call the guy who owns the corner store across the street cuz he owns a machete" (laughs). That\'s a response but its not transformative. It is totally about threatening.'
        + '<br><br>' + '<strong>That\'s one of those questions as a movement we have to [ask ourselves]</strong>. I don\'t think we\'ve fully grappled with the fact that a lot of us deep down, whether or not we say it or not, we think that sometimes de-escalating is about a power play.',
        personId: 7
      },
      {
        tagline: 'Friend supporters',
        quote: 'We let perpetuators invite a <strong>silent witness</strong> to the first meeting with us, and why I think it\'s so useful is because that\'s a person in the world to check them, that\'s a <strong>person that they trust who encourages them to go this route</strong>. It\'s one way of inviting in other members of the community.'
        + '<br><br>' + 'As I\'ve said, I think really having people who support that person [is important], but <strong>they have to support that person by wanting them to stop being harmful</strong>. A friend who says, "I\'m going to be with you at the bar and when this person asks you to leave, I\'m going to encourage you to leave. I\'m going to check in and make sure you are going to therapy."',
        personId: 18
      },
      {
        tagline: 'Relationships are the glue',
        quote: 'We should focus more on the <strong>relationship building and the base building</strong> aspects of the work before we delve into incidents. Granted, sometimes that\'s a luxury and sometimes that means a lot of really hard "no\'s" or really hard shifts if you\'re the only ones [providing services or support].'
        + '<br><br>' + 'I think that building those relationships makes our incident-based work much better. I think it <strong>makes our processes better</strong>, because if you have strong relationships, it is actually the <strong>glue that helps hold someone</strong>. It gives somebody a community that holds them accountable, beyond the organization or collective working on the process. So coming in to working with someone who has harmed, you know their parents, their cousins, where they go – you have this range of relationships, <strong>the information you get is different, the support that they get is different, and the folks who are holding them accountable is broader</strong>.',
        personId: 7
      },
      {
        tagline: 'Service provider network',
        quote: 'So we focus our work on <strong>three different spheres</strong>, that sort of roughly map onto the survivors of harm, people who have harmed, and then bystanders or community. First of all, we\'re developing a <strong>network of service providers</strong>, who would support a transformative justice, community accountability intervention. What we know to be true is that we don\'t have what we need. In an ideal world there would be survivor circles where healing and justice were happening and accountability circles where people who\'ve harmed are able to talk about their experiences and have support and accountability and healing. There would be free health care and massage and body work and all of these things that people need to live well. But as we know, that isn\'t the case, and so we see one really important piece of our work is <strong>building up access to those sort of supports</strong>. So one sphere of our work right now is connecting with the people who are already doing that work, getting them involved and invested in transformative justice and community accountability, and then being able to tap those people when we\'re in an intervention and say, "Hey, we\'re doing this thing with this person who\'s caused harm, we can use your facilitation skills, can you donate those to us?" or "This person really needs help finding a job, can you help do that for us?" So that\'s sort of one sphere of our work, which we refer to as the \'provider network\', so <strong>building a group of community service providers who have knowledge of and investment in transformative justice, who are going to be able to support our work</strong>. Because we can\'t offer all of those things on our own',
        personId: 16
      },
      {
        tagline: 'Giving cases back to community',
        quote: 'There are a couple processes that were not a hundred percent successful, did not turn out the way I would have loved them to. We were working on <strong>final statements</strong> that say: these are the things that we touched on, <strong>these demands were met</strong>, but we really felt that <strong>these issues could still be worked on</strong>, and so it\'s pending. We don\'t necessarily have an end point.'
        + '<br><br>' + 'We might hit a point where we say, "<strong>Okay, this isn\'t going anywhere.</strong>" If we feel we\'re lost. We\'ve also had people who are like, "No, I\'m fine, I\'ll keep meeting, yeah, let\'s do this." But then it doesn\'t feel like they are making a lot of progress. We are not just going to keep hammering it in, wasting our time. Rather just be like, "<strong>Okay, so maybe this isn\'t the best place for you to deal with this</strong>." That\'s another way of ending it and being a little bit more detailed about what was accomplished there and further points to go.'
        + '<br><br>' + 'But if it just seems like a <strong>failure</strong> and the person is totally still denying abuse and just doing the same behaviors, then the response is going to be something that becomes more of a <strong>public call-out</strong>. I feel like there should be <strong>some consequences to not finishing a process</strong>.'
        + '<br><br>' + 'So I guess, ideally, you would envision this process of accountability never really ending. It is something that <strong>everybody has to deal with throughout their entire lives but our endpoint is a way of handing it back to the community</strong>. That\'s hard because community is so broad and who knows.',
        personId: 18
      },
      {
        tagline: 'Accountability to communities',
        quote: 'Another place that accountability and community come up is the question of accountability to the community. So when you are saying community accountability, I hear <strong>accountability within communities</strong>. When I hear people talking about <strong>accountability to communities</strong>, they are talking about the <strong>challenges of the 501c3 non-profit structure</strong> in terms of community accountability.'
        + '<br><br>' + 'For example, at a recent conference there was a really powerful conversation about whether boards were organs of community accountability, or whether boards were barriers to community accountability. Meaning accountability to the community, organizations being accountable to the community, <strong>organizations as holders of resources which theoretically belong to all of us, being responsible to the community</strong>. So I feel like that\'s where I\'m mostly hearing the conversation, not so much in terms of community accountability models around how do we hold one another accountable around committing harm or around perpetration.'
        + '<br><br>' + 'Again, more in terms of management, <strong>how do I as your manager hold you as my subordinate accountable to your learning goals</strong>? And I do think some of the interpersonal accountability practices are related to community accountability. I believe there is probably a set of <strong>core accountability competencies</strong> or practices that <strong>we could map on an individual, interpersonal, and community level</strong>. So they are not unrelated.',
        personId: 8
      }
    ]
  },
  {
    title: 'What challenges have you faced working with communities?',
    nav: 'Challenges',
    question: '',
    quotes: [
      {
        tagline: 'Perpetuator is hero',
        quote: 'I think it\'s realistic to <strong>ask certain people who do a lot of community-based work and are really involved to step down</strong> from that while they work on challenging themselves in an accountability process. That\'s something I\'d like to see be more acceptable and common. But I think that\'s really hard because some people are important: "Oh I have to do this work to." But I mean, that work does really get in the way of a process with people who are already emotionally overwhelmed and busy.'
        + '<br><br>' + 'There\'s a <strong>big struggle when someone is a hero</strong>, because it\'s really hard for organizations to figure out: What do we do? Do we just drop this person? \'Well that\'s not what we [Support New York] are asking for. I keep thinking of Julian Assange, because I see so much of that: people <strong>lionizing a person as such a valuable activist, who\'s "done so much for us," and therefore erasing everything that they\'ve done that\'s harmful</strong>.'
        + '<br><br>' + 'People are not really able to have a parallel analysis. It\'s hard for people around the person causing harm to understand how <strong>people are more complicated than just really, really good or really, really bad</strong>. While the work from a person causing harm might be valuable for an organization, people\'s lives and safety and sexual health are also valuable, and that person has done helpful and harmful things.'
        + '<\/br>' + 'Plus, we hear the request from survivors a lot to <strong>get people causing harm out of mentorship roles</strong>, where they are in situations of power or meeting new people who they might be educating, etc. Some people in the organization are like, \'Why is this person being punished, why can\'t they do the work they do?\' and We say, \'Why don\'t they do the work without mentoring people?\''
        + '<br><br>' + 'Then there\'s a whole other conversation about <strong>male work and female work</strong>. It\'s so gendered, who becomes the public face of a group and who gets to do certain \'important\' work and who ends up doing the work that\'s necessary to sustain things and keep it together, the \'shit\' that isn\'t public and respectable: standing at the doorway greeting everybody at the party, tabling, chopping the fucking onions, right? There are things you can do to still get work done and be more behind the scenes. We try to <strong>challenge persons causing harm who want to stay involved in their political work to fulfill the less public and getting-all-the-back-patting roles</strong>. For us, it\'s like "Why don\'t they find a way to do the work a little more behind scenes, why don\'t they find a way to be more supportive?" Because in general, they need to be more supportive.',
        personId: 18
      },
      {
        tagline: 'Not hurting organization\'s good work',
        quote: '[Talking about organizations falling apart because they are unable to deal with sexual violence within the organization]'
        + '<br><br>' +'It showed up in the report ["Communities Engaged in Resisting Violence"], there\'s a whole section on creating organizational structures because of that. People know of organizations where the male director harasses all the women in the organization or there\'s a guy who works with you and he\'s had relationships with a series of fourteen-year-olds. There are all these examples that people would know about but not want to talk about for fear of harming organizations, right?'
        + '<br><br>' +'So the question of \'<strong>how do you respond to this in a way that\'s transformative, that has accountability for a perpetrator of physical or sexual violence, but doesn\'t hurt the very good cause the organization stands for?<strong>\' is really hard to figure out.'
        + '<br><br>' +'We tried it through the <strong>healing circle<strong> that was in the report. That was <strong>pretty successful in protecting people but not with accountability<strong>, because the perpetrator just said "I take no responsibility" and that was that. The circle was not an accountability circle, it was really for the survivor and the community. Then the community together with the survivor came up with a strategy of how to approach the perpetrator. And that\'s when things didn\'t go super well. We offered a time to all meet and do a circle, but he didn\'t want any of that. That\'s okay in that other good things came from it, but it\'s very hard to figure out.',
        personId: 6
      },
      {
        tagline: 'Community limitations',
        quote: '<strong>I want to believe that our communities can do everything</strong>, that our communities can be everything that we want and need them to be... They are sort of this dream that we could exist outside of the world as it exists right now and outside of particularly the way that states are using violence. And then it comes up against very real <strong>capacity issues, limits</strong> around what our skill bases actually are, what we\'re actually able to do, and follow through on.'
        + '<br><br>' + 'We talk about community and <strong>no one really knows what community is</strong>. We all kind of have this idea of what it is. "Oh, the community is responding and wants this and this and this" but really, just cuz we\'re a community doesn\'t mean that all of our <strong>power dynamics</strong> aren\'t going to play out. And we should expect them to play out. I think it\'s easy for us to <strong>idealize community</strong> and assume, "Well if the community wanted it then.. we\'re all good."'
        + '<br><br>' + 'For me, accountability is a lot of doing what you say you\'re gonna do, and sometimes I feel like in the transformative justice models, <strong>we\'re not actually able to do all the things that we want to do</strong>, or say we want to do.'
        + '<br><br>' + 'Is it better to be like, "Well, we\'ve got nothing" or is it better to be like, "We could try this thing and it probably is gonna be weird and I hope that it goes well and here are all the values its based on, which sounds really cool and in line with our values, but we don\'t really know how to do it yet."',
        personId: 4
      },
      {
        tagline: 'Community status in limbo',
        quote: 'If a process is kind of public, and everybody knows that this person\'s in a process, I\'ve also had the experience of <strong>somebody trying really hard to change and not get recognition from the community</strong>. People were like, "Oh well, you\'re in an accountability process so what does that say about you. You\'re a fuck up, whatever." When somebody\'s trying really hard for themselves to change but their public image doesn\'t change, it\'s hard, because we can\'t really give any guarantees that once they go through the process, they are just going to be accepted back with people.'
        + '<br><br>' + 'On the flip side, being in a process is sort of <strong>limbo</strong> in some ways. It\'s limbo in that, in one case I know, it suspended critique of the person, because he could respond to any criticism by saying, \'Oh, I\'m in a process.\' <strong>When the process was put on hold because of problems, so was the critique of that person</strong>. So, there are two sides to that.',
        personId: 18
      }
    ]
  },
  {
    title: 'How are community-based responses transforming our relationship to the State?',
    nav: 'State & Beyond',
    question: '',
    quotes: [
      {
        tagline: 'Give you the phone, but I won\'t call',
        quote: '<strong>Keeping the state out</strong> is usually something that I prioritize, but I don\'t want to limit a survivor\'s ability to make whatever choices they need to make. <strong>I could give someone the phone but I\'m not going to call the cops</strong>, just knowing that that\'s my own boundary.',
        personId: 4
      },
      {
        tagline: 'State\'s taken over lives',
        quote: 'Because of the way the state works in the U.S. and because of the communities that we\'re prioritizing working with, it feels like there\'s just <strong>no way to get the state out of their lives</strong>. If we\'re working mostly with queer people of color, so many of those folks are dependent on the state and are being pushed and pulled by the state in all sorts of different ways, that being separate from that feels impossible. That\'s a difference that comes up when we talk with groups of people coming out of the white punk scene in the U.S., is that there\'s no option of being fully separate from the state. The <strong>state has taken over these lives</strong>.',
        personId: 16
      },
      {
        tagline: 'New state vs. outside the state',
        quote: 'Most of the accountability folks who are putting their theory out there either have a <strong>revolutionary rhetoric</strong> or they have an <strong>anarchist</strong> one. And it sometimes unstable, right, it will move between those two. Either we are going to have a <strong>wholly new state born of this</strong>, or it is about <strong>living outside of the state, or living in places the state isn\'t looking at</strong>, and maybe something new will come of that.'
        + '<br><br>' +'"What are you already doing to try to address the violence that is happening?" [People] have more skills than they knew they did. <strong>This is already the alternative underway. This is already a new form of life being developed in the midst of this form of life</strong>, but how do you articulate that? And how do you show, how do you give evidence-based research that this is having an effect? How do you quantify it for people who want to know what to do with the \'worst of the worst\'? So I do think a lot more work needs to happen...'
        + '<br><br>' +'Well I don\'t know I\'m really torn about this, because in some ways the <strong>mechanisms for legitimating community accountability are the old mechanisms of the carceral state</strong>. So, in some ways I\'m really happy to have this work to be happening under the radar, and in these very interstitial spaces where it\'s not clear where the outcome is going to be, it\'s not clear what\'s going to happen next, because that in some way <strong>escapes the carceral state</strong>, or it happens just under the radar within it. But if prisons are going to be abolished, if we are going to live in a world without rape and without sexual assault, and I think we can, then <strong>we have to scale it up or we have to articulate it in ways that more people can interact with and understand and buy into</strong>. I don\'t think I\'m ready to give up the state, you know, but I think Wendy Brown is so right about feminists needing to stop thinking that the \'daddy state\' is going come save us from patriarchy.',
        personId: 3
      },
      {
        tagline: 'Between revolution & reform',
        quote: '<strong>My organizing career hops back and forth between those things [revolution and reform]</strong> and I like to stay in that space because I feel like that\'s the space I learn the most. If I hadn\'t worked on a lot of reform, I wouldn\'t have been able to concretize and to lay out a concrete plan for SOS [Safe Outside the System]\'s work. And all the revolutionary ideas that I bring means that I think broader when it comes to reform strategies. I think we need both, and <strong>the more we silo, the less effective we are, because there\'s utility in both approaches</strong>.'
        + '<br><br>' +'I think in New York that\'s one of the things people are struggling with. So we\'ve done a lot of awesome organizing around police reform. We actually are winning things, which was a fifteen year struggle to get back here because from Diallo and then after 9\/11, it was really hard to organize against the police or any State anything. But there\'s a lot of <strong>conflict between the prison abolitionists and the police reform folks</strong>. I really wish we could take that conflict away, that conflict is wasting energy.'
        + '<br><br>' +'<strong>We don\'t actually have to have arguments between reform and revolution</strong>. We can make reform the step. Let\'s just be super strategic with our reform. Let\'s be really clear on the idea that \'<strong>this is harm-reduction around the State</strong>.\' And there are State-based approaches that can be interesting. What would it mean to lobby and work towards community mediation centers?',
        personId: 7
      },
      {
        tagline: 'People\'s ambulance',
        quote: 'Harm brings up that urgency [of an alternative]. Leah Lakshmi Piepzna-Samarasinha\'s work is saying, like "Okay, <strong>where is the people\'s ambulance</strong>? You know, like, we have needs! We have health needs, we have emergency needs! We have emergencies!" That\'s emerging. But we don\'t have the people\'s ambulance. She\'s one of the main, major people who is doing safety team work and safe party work and creating systems of response in movement spaces, as practice.'
        + '<br><br>' +'So harm, emergency response is the point at which you start wondering about <strong>scale</strong>. How many people does it take to make this work? It becomes so concrete and urgent, and you know it\'s the moments where <strong>we are forced to depend on the state. You do have to go to the emergency room, whatever you believe</strong>. However anti-authoritarian and anarchist I am, if it\'s me and the people that I love \'bout to bleed out, I\'m not going to pretend the state doesn\'t exist! There\'s not an alternative that I can say, \'Everybody, let\'s suture this persons wounds!\' (laughs). It\'s not operationalized in that way, although all of that is there',
        personId: 1
      },
      {
        tagline: 'Resist or govern?',
        quote: 'So one of the ways this came up was when <strong>Move to End Violence\'s first cohort traveled to India to meet with sister organizations organizing around women\'s issues</strong> more broadly, and sex trafficking, violence against women and girls. And one of the things that they came back with that was really interesting was feeling like they\'d been <strong>challenged by their sisters</strong> there, who really challenged them about abandoning the state, and saying "<strong>Why are you not holding the state accountable</strong>?" Again, a human rights frame would say "If these are human rights, we demand them from our state nationally and from our states internationally." That there is actually global power in that frame and that organizing platform. I think there is a lot of truth to that.'
        + '<br><br>' +'At the same time, I am really with the notion that the <strong>state is so profoundly absent, corrupt... absent or corrupt, these seem to be the options (laughs), that we need alternatives, we need to imagine alternatives</strong>.'
        + '<br><br>' +'So for me, where the dilemma, <strong>how the dilemma lives is the difference between resistance and government</strong>. I worry sometimes that <strong>on the Left, and even in our most radical queer feminist organizing spaces, that we exercise our muscles around resistance much more than we exercise our muscles around governance</strong>. And I think that it is a worthwhile challenge, and <strong>it will actually be required of us to be able to govern</strong>. So I am <strong>not willing to abandon the state nor do I think we can afford to stop imagining and seeding and living alternatives</strong>, living into those alternatives. And I do really challenge us about are we able only to resist or to govern? When we look at revolutionary movements globally, that is a challenge, that \'all resistance and no government\' doesn\'t actually get you very far.  [\']',
        personId: 8
      },
      {
        tagline: 'Queer Black state',
        quote: 'If we are here and we are clear that <strong>recognition from an existing state is not getting our needs met, then that state fails</strong>. But <strong>what is a unit that counts itself and meets its needs? Is that a state?</strong> It might not be like nation-state. But is that a state?'
        + '<br><br>' +'These calls for community, to the \'this community,\' to the \'that community,\' the queer community, it makes me want to ask: <strong>Is what we are really desiring and creating a state?</strong> Are we creating an alternative state?'
        + '<br><br>' +'There\'s something very challenging in that for me, because, I mean, <strong>that\'s terrible news!</strong> (laughs) Every state I\'ve ever heard about is violent, the form of the state is violent.'
        + '<br><br>' +'But, is that not it? <strong>Do we want a queer community, a Black community or do we want a queer state!? Do we want a Black state?!</strong> Is it possible to actually create a sustainable alternative state of being without doing state-type stuff?',
        personId: 1
      },
      {
        tagline: 'Neighborhood replaces the PIC',
        quote: 'By the time I left Women and Girls CAN, I felt like we had come up with a lot of <strong>theories that were right on, and the implementation of them is so challenging<strong>.  I feel like there are very few examples right now [in 2013] of where they\'ve been implemented in a <strong>sustainable<strong> way. It\'s easy to come up with examples - like our healing circle. Or another example, here was an act of violence and the community came together, because the right people were at the table and somebody was trained in restorative justice, and they came up with a process and it was good.'
        + '<br><br>' +'But that\'s really different than saying: <strong>Let\'s take a community in Chicago, a whole neighborhood in Chicago. And let\'s remove the PIC and remove the traditional ways of going to social service agencies and traditional shelters<strong> which are so problematic most of the time. Let\'s take all that out and <strong>what infrastructure do we put in its place that can really respond to violence<strong>. I haven\'t seen that yet. I think Mimi Kim in California did some interesting work, we were looking at that very closely. Not even going neighborhood-wide, just a ten block radius, <strong>how do you set something up that really kept people safe and responded to acts of violence and prevented acts of violence and didn\'t rely on any of the traditional structures<strong>?',
        personId: 6
      },
      {
        tagline: 'Ambivalent about power',
        quote: 'Well, I think it is quite related, on a individual and group level, I think we are <strong>deeply ambivalent about power, partly because we imagine power only as we\'ve seen it abused</strong>. Again, thinking about the violence frame and thinking about the families and communities that many of us grow up in, like <strong>what other forms of power have we seen, besides power that is abusive?</strong> So I think there\'s a way that we have <strong>merged power and abuse as if they were the same thing</strong>, and it is hard for us to imagine that we could have <strong>positive power, co- power, power with</strong>...'
        + '<br><br>' +'Even though we use the word \'empowerment,\' I think on some level we think that all forms of power, and authority, meaning the right to make binding decisions over others, are inherently abusive. That, I think, is quite tricky, particularly when we are trying to organize with other people when everyone is ambivalent about power, and about authority, right? We are unwilling to differentiate roles, or to have different relationships with authority, or imagine even that we can function successfully in a hierarchy if it served a particular strategic purpose, and then change our shape if we needed to do something else. So organizationally I\'ve been thinking about, as <strong>we get clearer and warmer towards authority and power, I think there\'s actually a way in which we become more nimble</strong>. And our organizations can change shape depending on the work that we have to do. Because there are times when what you need is hierarchy to get something done quickly, as opposed to a network.'
        + '<br><br>' +'I\'ve thought about this the most coming from the culture of the movement around sexual violence, but I think that there is a <strong>relationship between our experiences of abuse and trauma and our ambivalence around power</strong>. At the same time, there is our unwillingness to call out one another when we see one another and people who look like us being abusive, our reluctance to call those folks out because we\'ve created this <strong>dichotomy</strong> that you are either good or bad, you are either victim or perpetrator, and since you are a victim, you couldn\'t possibly be perpetrating, even though your behavior is in fact abusive. So <strong>we have locked ourselves into these categories that prevent ourselves from really governing, from really seizing, taking, using, moving with and operating with power</strong>. I think we have a lot of work to do. And interestingly, just looping back, I think some of those <strong>embodied transformational practices</strong> are getting at that, are enabling folks to play with and explore power individually and in groups in ways that are unlocking something.',
        personId: 8
      },
      {
        tagline: 'Scale it up',
        quote: 'But if prisons are going to be abolished, if we are going to live in a world without rape and without sexual assault, and I think we can, then we have to <strong>scale it up or we have to articulate it in ways that more people can interact with and understand and buy into</strong>.',
        personId: 3
      },
      {
        tagline: 'Question of scale',
        quote: 'On what <strong>scale</strong> are we willing to do [state-type stuff], on what scale is it appropriate to do that? If we want to create something different, are we willing to say or even experiment with...<strong>what about a state of 7</strong>? What is the <strong>difference between a state and a household</strong>? Are these the scales that we want to operate on?'
        + '<br><br>' +'And how concrete are we willing to be in what we would want to replace the present state? You know, like what are <strong>future states of being</strong> that we would be willing to imagine concretely enough to commit to? And would we be willing to do that, is it possible to do that, to create a state, in a way that still acknowledges the need for the poetic intervention, the <strong>inevitable insufficiency of a state</strong>.',
        personId: 1
      }
    ]
  }
];
